// Code generated by entc, DO NOT EDIT.

package targetarea

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Continent applies equality check predicate on the "continent" field. It's identical to ContinentEQ.
func Continent(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContinent), v))
	})
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCountry), v))
	})
}

// ContinentEQ applies the EQ predicate on the "continent" field.
func ContinentEQ(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldContinent), v))
	})
}

// ContinentNEQ applies the NEQ predicate on the "continent" field.
func ContinentNEQ(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldContinent), v))
	})
}

// ContinentIn applies the In predicate on the "continent" field.
func ContinentIn(vs ...string) predicate.TargetArea {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TargetArea(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldContinent), v...))
	})
}

// ContinentNotIn applies the NotIn predicate on the "continent" field.
func ContinentNotIn(vs ...string) predicate.TargetArea {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TargetArea(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldContinent), v...))
	})
}

// ContinentGT applies the GT predicate on the "continent" field.
func ContinentGT(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldContinent), v))
	})
}

// ContinentGTE applies the GTE predicate on the "continent" field.
func ContinentGTE(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldContinent), v))
	})
}

// ContinentLT applies the LT predicate on the "continent" field.
func ContinentLT(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldContinent), v))
	})
}

// ContinentLTE applies the LTE predicate on the "continent" field.
func ContinentLTE(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldContinent), v))
	})
}

// ContinentContains applies the Contains predicate on the "continent" field.
func ContinentContains(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldContinent), v))
	})
}

// ContinentHasPrefix applies the HasPrefix predicate on the "continent" field.
func ContinentHasPrefix(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldContinent), v))
	})
}

// ContinentHasSuffix applies the HasSuffix predicate on the "continent" field.
func ContinentHasSuffix(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldContinent), v))
	})
}

// ContinentEqualFold applies the EqualFold predicate on the "continent" field.
func ContinentEqualFold(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldContinent), v))
	})
}

// ContinentContainsFold applies the ContainsFold predicate on the "continent" field.
func ContinentContainsFold(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldContinent), v))
	})
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCountry), v))
	})
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCountry), v))
	})
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.TargetArea {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TargetArea(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCountry), v...))
	})
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.TargetArea {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TargetArea(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCountry), v...))
	})
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCountry), v))
	})
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCountry), v))
	})
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCountry), v))
	})
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCountry), v))
	})
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldCountry), v))
	})
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldCountry), v))
	})
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldCountry), v))
	})
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldCountry), v))
	})
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldCountry), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TargetArea) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TargetArea) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TargetArea) predicate.TargetArea {
	return predicate.TargetArea(func(s *sql.Selector) {
		p(s.Not())
	})
}
