// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/appgoodpromotion"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppGoodPromotionQuery is the builder for querying AppGoodPromotion entities.
type AppGoodPromotionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppGoodPromotion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppGoodPromotionQuery builder.
func (agpq *AppGoodPromotionQuery) Where(ps ...predicate.AppGoodPromotion) *AppGoodPromotionQuery {
	agpq.predicates = append(agpq.predicates, ps...)
	return agpq
}

// Limit adds a limit step to the query.
func (agpq *AppGoodPromotionQuery) Limit(limit int) *AppGoodPromotionQuery {
	agpq.limit = &limit
	return agpq
}

// Offset adds an offset step to the query.
func (agpq *AppGoodPromotionQuery) Offset(offset int) *AppGoodPromotionQuery {
	agpq.offset = &offset
	return agpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agpq *AppGoodPromotionQuery) Unique(unique bool) *AppGoodPromotionQuery {
	agpq.unique = &unique
	return agpq
}

// Order adds an order step to the query.
func (agpq *AppGoodPromotionQuery) Order(o ...OrderFunc) *AppGoodPromotionQuery {
	agpq.order = append(agpq.order, o...)
	return agpq
}

// First returns the first AppGoodPromotion entity from the query.
// Returns a *NotFoundError when no AppGoodPromotion was found.
func (agpq *AppGoodPromotionQuery) First(ctx context.Context) (*AppGoodPromotion, error) {
	nodes, err := agpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appgoodpromotion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) FirstX(ctx context.Context) *AppGoodPromotion {
	node, err := agpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppGoodPromotion ID from the query.
// Returns a *NotFoundError when no AppGoodPromotion ID was found.
func (agpq *AppGoodPromotionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appgoodpromotion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := agpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppGoodPromotion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AppGoodPromotion entity is not found.
// Returns a *NotFoundError when no AppGoodPromotion entities are found.
func (agpq *AppGoodPromotionQuery) Only(ctx context.Context) (*AppGoodPromotion, error) {
	nodes, err := agpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appgoodpromotion.Label}
	default:
		return nil, &NotSingularError{appgoodpromotion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) OnlyX(ctx context.Context) *AppGoodPromotion {
	node, err := agpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppGoodPromotion ID in the query.
// Returns a *NotSingularError when exactly one AppGoodPromotion ID is not found.
// Returns a *NotFoundError when no entities are found.
func (agpq *AppGoodPromotionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = &NotSingularError{appgoodpromotion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := agpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppGoodPromotions.
func (agpq *AppGoodPromotionQuery) All(ctx context.Context) ([]*AppGoodPromotion, error) {
	if err := agpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return agpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) AllX(ctx context.Context) []*AppGoodPromotion {
	nodes, err := agpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppGoodPromotion IDs.
func (agpq *AppGoodPromotionQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := agpq.Select(appgoodpromotion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := agpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agpq *AppGoodPromotionQuery) Count(ctx context.Context) (int, error) {
	if err := agpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return agpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) CountX(ctx context.Context) int {
	count, err := agpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agpq *AppGoodPromotionQuery) Exist(ctx context.Context) (bool, error) {
	if err := agpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return agpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (agpq *AppGoodPromotionQuery) ExistX(ctx context.Context) bool {
	exist, err := agpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppGoodPromotionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agpq *AppGoodPromotionQuery) Clone() *AppGoodPromotionQuery {
	if agpq == nil {
		return nil
	}
	return &AppGoodPromotionQuery{
		config:     agpq.config,
		limit:      agpq.limit,
		offset:     agpq.offset,
		order:      append([]OrderFunc{}, agpq.order...),
		predicates: append([]predicate.AppGoodPromotion{}, agpq.predicates...),
		// clone intermediate query.
		sql:  agpq.sql.Clone(),
		path: agpq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppGoodPromotion.Query().
//		GroupBy(appgoodpromotion.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (agpq *AppGoodPromotionQuery) GroupBy(field string, fields ...string) *AppGoodPromotionGroupBy {
	group := &AppGoodPromotionGroupBy{config: agpq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := agpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return agpq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.AppGoodPromotion.Query().
//		Select(appgoodpromotion.FieldAppID).
//		Scan(ctx, &v)
//
func (agpq *AppGoodPromotionQuery) Select(fields ...string) *AppGoodPromotionSelect {
	agpq.fields = append(agpq.fields, fields...)
	return &AppGoodPromotionSelect{AppGoodPromotionQuery: agpq}
}

func (agpq *AppGoodPromotionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range agpq.fields {
		if !appgoodpromotion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agpq.path != nil {
		prev, err := agpq.path(ctx)
		if err != nil {
			return err
		}
		agpq.sql = prev
	}
	return nil
}

func (agpq *AppGoodPromotionQuery) sqlAll(ctx context.Context) ([]*AppGoodPromotion, error) {
	var (
		nodes = []*AppGoodPromotion{}
		_spec = agpq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AppGoodPromotion{config: agpq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, agpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (agpq *AppGoodPromotionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agpq.querySpec()
	_spec.Node.Columns = agpq.fields
	if len(agpq.fields) > 0 {
		_spec.Unique = agpq.unique != nil && *agpq.unique
	}
	return sqlgraph.CountNodes(ctx, agpq.driver, _spec)
}

func (agpq *AppGoodPromotionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := agpq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (agpq *AppGoodPromotionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appgoodpromotion.Table,
			Columns: appgoodpromotion.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appgoodpromotion.FieldID,
			},
		},
		From:   agpq.sql,
		Unique: true,
	}
	if unique := agpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := agpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appgoodpromotion.FieldID)
		for i := range fields {
			if fields[i] != appgoodpromotion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agpq *AppGoodPromotionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agpq.driver.Dialect())
	t1 := builder.Table(appgoodpromotion.Table)
	columns := agpq.fields
	if len(columns) == 0 {
		columns = appgoodpromotion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if agpq.sql != nil {
		selector = agpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if agpq.unique != nil && *agpq.unique {
		selector.Distinct()
	}
	for _, p := range agpq.predicates {
		p(selector)
	}
	for _, p := range agpq.order {
		p(selector)
	}
	if offset := agpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppGoodPromotionGroupBy is the group-by builder for AppGoodPromotion entities.
type AppGoodPromotionGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agpgb *AppGoodPromotionGroupBy) Aggregate(fns ...AggregateFunc) *AppGoodPromotionGroupBy {
	agpgb.fns = append(agpgb.fns, fns...)
	return agpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (agpgb *AppGoodPromotionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := agpgb.path(ctx)
	if err != nil {
		return err
	}
	agpgb.sql = query
	return agpgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := agpgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(agpgb.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := agpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) StringsX(ctx context.Context) []string {
	v, err := agpgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = agpgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) StringX(ctx context.Context) string {
	v, err := agpgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(agpgb.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := agpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) IntsX(ctx context.Context) []int {
	v, err := agpgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = agpgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) IntX(ctx context.Context) int {
	v, err := agpgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(agpgb.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := agpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := agpgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = agpgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) Float64X(ctx context.Context) float64 {
	v, err := agpgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(agpgb.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := agpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := agpgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agpgb *AppGoodPromotionGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = agpgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (agpgb *AppGoodPromotionGroupBy) BoolX(ctx context.Context) bool {
	v, err := agpgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (agpgb *AppGoodPromotionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range agpgb.fields {
		if !appgoodpromotion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := agpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (agpgb *AppGoodPromotionGroupBy) sqlQuery() *sql.Selector {
	selector := agpgb.sql.Select()
	aggregation := make([]string, 0, len(agpgb.fns))
	for _, fn := range agpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(agpgb.fields)+len(agpgb.fns))
		for _, f := range agpgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(agpgb.fields...)...)
}

// AppGoodPromotionSelect is the builder for selecting fields of AppGoodPromotion entities.
type AppGoodPromotionSelect struct {
	*AppGoodPromotionQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (agps *AppGoodPromotionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := agps.prepareQuery(ctx); err != nil {
		return err
	}
	agps.sql = agps.AppGoodPromotionQuery.sqlQuery(ctx)
	return agps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) ScanX(ctx context.Context, v interface{}) {
	if err := agps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) Strings(ctx context.Context) ([]string, error) {
	if len(agps.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := agps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) StringsX(ctx context.Context) []string {
	v, err := agps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = agps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) StringX(ctx context.Context) string {
	v, err := agps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) Ints(ctx context.Context) ([]int, error) {
	if len(agps.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := agps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) IntsX(ctx context.Context) []int {
	v, err := agps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = agps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) IntX(ctx context.Context) int {
	v, err := agps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(agps.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := agps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) Float64sX(ctx context.Context) []float64 {
	v, err := agps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = agps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) Float64X(ctx context.Context) float64 {
	v, err := agps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(agps.fields) > 1 {
		return nil, errors.New("ent: AppGoodPromotionSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := agps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) BoolsX(ctx context.Context) []bool {
	v, err := agps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (agps *AppGoodPromotionSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = agps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodpromotion.Label}
	default:
		err = fmt.Errorf("ent: AppGoodPromotionSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (agps *AppGoodPromotionSelect) BoolX(ctx context.Context) bool {
	v, err := agps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (agps *AppGoodPromotionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := agps.sql.Query()
	if err := agps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
