// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/appgoodtargetarea"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// AppGoodTargetAreaQuery is the builder for querying AppGoodTargetArea entities.
type AppGoodTargetAreaQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppGoodTargetArea
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppGoodTargetAreaQuery builder.
func (agtaq *AppGoodTargetAreaQuery) Where(ps ...predicate.AppGoodTargetArea) *AppGoodTargetAreaQuery {
	agtaq.predicates = append(agtaq.predicates, ps...)
	return agtaq
}

// Limit adds a limit step to the query.
func (agtaq *AppGoodTargetAreaQuery) Limit(limit int) *AppGoodTargetAreaQuery {
	agtaq.limit = &limit
	return agtaq
}

// Offset adds an offset step to the query.
func (agtaq *AppGoodTargetAreaQuery) Offset(offset int) *AppGoodTargetAreaQuery {
	agtaq.offset = &offset
	return agtaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agtaq *AppGoodTargetAreaQuery) Unique(unique bool) *AppGoodTargetAreaQuery {
	agtaq.unique = &unique
	return agtaq
}

// Order adds an order step to the query.
func (agtaq *AppGoodTargetAreaQuery) Order(o ...OrderFunc) *AppGoodTargetAreaQuery {
	agtaq.order = append(agtaq.order, o...)
	return agtaq
}

// First returns the first AppGoodTargetArea entity from the query.
// Returns a *NotFoundError when no AppGoodTargetArea was found.
func (agtaq *AppGoodTargetAreaQuery) First(ctx context.Context) (*AppGoodTargetArea, error) {
	nodes, err := agtaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{appgoodtargetarea.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) FirstX(ctx context.Context) *AppGoodTargetArea {
	node, err := agtaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppGoodTargetArea ID from the query.
// Returns a *NotFoundError when no AppGoodTargetArea ID was found.
func (agtaq *AppGoodTargetAreaQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agtaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{appgoodtargetarea.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := agtaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppGoodTargetArea entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AppGoodTargetArea entity is not found.
// Returns a *NotFoundError when no AppGoodTargetArea entities are found.
func (agtaq *AppGoodTargetAreaQuery) Only(ctx context.Context) (*AppGoodTargetArea, error) {
	nodes, err := agtaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{appgoodtargetarea.Label}
	default:
		return nil, &NotSingularError{appgoodtargetarea.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) OnlyX(ctx context.Context) *AppGoodTargetArea {
	node, err := agtaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppGoodTargetArea ID in the query.
// Returns a *NotSingularError when exactly one AppGoodTargetArea ID is not found.
// Returns a *NotFoundError when no entities are found.
func (agtaq *AppGoodTargetAreaQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agtaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = &NotSingularError{appgoodtargetarea.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := agtaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppGoodTargetAreas.
func (agtaq *AppGoodTargetAreaQuery) All(ctx context.Context) ([]*AppGoodTargetArea, error) {
	if err := agtaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return agtaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) AllX(ctx context.Context) []*AppGoodTargetArea {
	nodes, err := agtaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppGoodTargetArea IDs.
func (agtaq *AppGoodTargetAreaQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := agtaq.Select(appgoodtargetarea.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := agtaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agtaq *AppGoodTargetAreaQuery) Count(ctx context.Context) (int, error) {
	if err := agtaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return agtaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) CountX(ctx context.Context) int {
	count, err := agtaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agtaq *AppGoodTargetAreaQuery) Exist(ctx context.Context) (bool, error) {
	if err := agtaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return agtaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (agtaq *AppGoodTargetAreaQuery) ExistX(ctx context.Context) bool {
	exist, err := agtaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppGoodTargetAreaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agtaq *AppGoodTargetAreaQuery) Clone() *AppGoodTargetAreaQuery {
	if agtaq == nil {
		return nil
	}
	return &AppGoodTargetAreaQuery{
		config:     agtaq.config,
		limit:      agtaq.limit,
		offset:     agtaq.offset,
		order:      append([]OrderFunc{}, agtaq.order...),
		predicates: append([]predicate.AppGoodTargetArea{}, agtaq.predicates...),
		// clone intermediate query.
		sql:  agtaq.sql.Clone(),
		path: agtaq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppGoodTargetArea.Query().
//		GroupBy(appgoodtargetarea.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (agtaq *AppGoodTargetAreaQuery) GroupBy(field string, fields ...string) *AppGoodTargetAreaGroupBy {
	group := &AppGoodTargetAreaGroupBy{config: agtaq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := agtaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return agtaq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.AppGoodTargetArea.Query().
//		Select(appgoodtargetarea.FieldAppID).
//		Scan(ctx, &v)
//
func (agtaq *AppGoodTargetAreaQuery) Select(fields ...string) *AppGoodTargetAreaSelect {
	agtaq.fields = append(agtaq.fields, fields...)
	return &AppGoodTargetAreaSelect{AppGoodTargetAreaQuery: agtaq}
}

func (agtaq *AppGoodTargetAreaQuery) prepareQuery(ctx context.Context) error {
	for _, f := range agtaq.fields {
		if !appgoodtargetarea.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agtaq.path != nil {
		prev, err := agtaq.path(ctx)
		if err != nil {
			return err
		}
		agtaq.sql = prev
	}
	return nil
}

func (agtaq *AppGoodTargetAreaQuery) sqlAll(ctx context.Context) ([]*AppGoodTargetArea, error) {
	var (
		nodes = []*AppGoodTargetArea{}
		_spec = agtaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AppGoodTargetArea{config: agtaq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, agtaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (agtaq *AppGoodTargetAreaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agtaq.querySpec()
	_spec.Node.Columns = agtaq.fields
	if len(agtaq.fields) > 0 {
		_spec.Unique = agtaq.unique != nil && *agtaq.unique
	}
	return sqlgraph.CountNodes(ctx, agtaq.driver, _spec)
}

func (agtaq *AppGoodTargetAreaQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := agtaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (agtaq *AppGoodTargetAreaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   appgoodtargetarea.Table,
			Columns: appgoodtargetarea.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appgoodtargetarea.FieldID,
			},
		},
		From:   agtaq.sql,
		Unique: true,
	}
	if unique := agtaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := agtaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appgoodtargetarea.FieldID)
		for i := range fields {
			if fields[i] != appgoodtargetarea.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agtaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agtaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agtaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agtaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agtaq *AppGoodTargetAreaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agtaq.driver.Dialect())
	t1 := builder.Table(appgoodtargetarea.Table)
	columns := agtaq.fields
	if len(columns) == 0 {
		columns = appgoodtargetarea.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if agtaq.sql != nil {
		selector = agtaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if agtaq.unique != nil && *agtaq.unique {
		selector.Distinct()
	}
	for _, p := range agtaq.predicates {
		p(selector)
	}
	for _, p := range agtaq.order {
		p(selector)
	}
	if offset := agtaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agtaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppGoodTargetAreaGroupBy is the group-by builder for AppGoodTargetArea entities.
type AppGoodTargetAreaGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agtagb *AppGoodTargetAreaGroupBy) Aggregate(fns ...AggregateFunc) *AppGoodTargetAreaGroupBy {
	agtagb.fns = append(agtagb.fns, fns...)
	return agtagb
}

// Scan applies the group-by query and scans the result into the given value.
func (agtagb *AppGoodTargetAreaGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := agtagb.path(ctx)
	if err != nil {
		return err
	}
	agtagb.sql = query
	return agtagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := agtagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(agtagb.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := agtagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) StringsX(ctx context.Context) []string {
	v, err := agtagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = agtagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) StringX(ctx context.Context) string {
	v, err := agtagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(agtagb.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := agtagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) IntsX(ctx context.Context) []int {
	v, err := agtagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = agtagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) IntX(ctx context.Context) int {
	v, err := agtagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(agtagb.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := agtagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := agtagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = agtagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) Float64X(ctx context.Context) float64 {
	v, err := agtagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(agtagb.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := agtagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := agtagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (agtagb *AppGoodTargetAreaGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = agtagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (agtagb *AppGoodTargetAreaGroupBy) BoolX(ctx context.Context) bool {
	v, err := agtagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (agtagb *AppGoodTargetAreaGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range agtagb.fields {
		if !appgoodtargetarea.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := agtagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agtagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (agtagb *AppGoodTargetAreaGroupBy) sqlQuery() *sql.Selector {
	selector := agtagb.sql.Select()
	aggregation := make([]string, 0, len(agtagb.fns))
	for _, fn := range agtagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(agtagb.fields)+len(agtagb.fns))
		for _, f := range agtagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(agtagb.fields...)...)
}

// AppGoodTargetAreaSelect is the builder for selecting fields of AppGoodTargetArea entities.
type AppGoodTargetAreaSelect struct {
	*AppGoodTargetAreaQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (agtas *AppGoodTargetAreaSelect) Scan(ctx context.Context, v interface{}) error {
	if err := agtas.prepareQuery(ctx); err != nil {
		return err
	}
	agtas.sql = agtas.AppGoodTargetAreaQuery.sqlQuery(ctx)
	return agtas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) ScanX(ctx context.Context, v interface{}) {
	if err := agtas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) Strings(ctx context.Context) ([]string, error) {
	if len(agtas.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := agtas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) StringsX(ctx context.Context) []string {
	v, err := agtas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = agtas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) StringX(ctx context.Context) string {
	v, err := agtas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) Ints(ctx context.Context) ([]int, error) {
	if len(agtas.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := agtas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) IntsX(ctx context.Context) []int {
	v, err := agtas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = agtas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) IntX(ctx context.Context) int {
	v, err := agtas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(agtas.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := agtas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) Float64sX(ctx context.Context) []float64 {
	v, err := agtas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = agtas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) Float64X(ctx context.Context) float64 {
	v, err := agtas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(agtas.fields) > 1 {
		return nil, errors.New("ent: AppGoodTargetAreaSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := agtas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) BoolsX(ctx context.Context) []bool {
	v, err := agtas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (agtas *AppGoodTargetAreaSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = agtas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{appgoodtargetarea.Label}
	default:
		err = fmt.Errorf("ent: AppGoodTargetAreaSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (agtas *AppGoodTargetAreaSelect) BoolX(ctx context.Context) bool {
	v, err := agtas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (agtas *AppGoodTargetAreaSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := agtas.sql.Query()
	if err := agtas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
