// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/migrate"
	"github.com/google/uuid"

	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/goodinfo"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/targetarea"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// GoodInfo is the client for interacting with the GoodInfo builders.
	GoodInfo *GoodInfoClient
	// TargetArea is the client for interacting with the TargetArea builders.
	TargetArea *TargetAreaClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.GoodInfo = NewGoodInfoClient(c.config)
	c.TargetArea = NewTargetAreaClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		GoodInfo:   NewGoodInfoClient(cfg),
		TargetArea: NewTargetAreaClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:     cfg,
		GoodInfo:   NewGoodInfoClient(cfg),
		TargetArea: NewTargetAreaClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		GoodInfo.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.GoodInfo.Use(hooks...)
	c.TargetArea.Use(hooks...)
}

// GoodInfoClient is a client for the GoodInfo schema.
type GoodInfoClient struct {
	config
}

// NewGoodInfoClient returns a client for the GoodInfo from the given config.
func NewGoodInfoClient(c config) *GoodInfoClient {
	return &GoodInfoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `goodinfo.Hooks(f(g(h())))`.
func (c *GoodInfoClient) Use(hooks ...Hook) {
	c.hooks.GoodInfo = append(c.hooks.GoodInfo, hooks...)
}

// Create returns a create builder for GoodInfo.
func (c *GoodInfoClient) Create() *GoodInfoCreate {
	mutation := newGoodInfoMutation(c.config, OpCreate)
	return &GoodInfoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GoodInfo entities.
func (c *GoodInfoClient) CreateBulk(builders ...*GoodInfoCreate) *GoodInfoCreateBulk {
	return &GoodInfoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GoodInfo.
func (c *GoodInfoClient) Update() *GoodInfoUpdate {
	mutation := newGoodInfoMutation(c.config, OpUpdate)
	return &GoodInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GoodInfoClient) UpdateOne(gi *GoodInfo) *GoodInfoUpdateOne {
	mutation := newGoodInfoMutation(c.config, OpUpdateOne, withGoodInfo(gi))
	return &GoodInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GoodInfoClient) UpdateOneID(id uuid.UUID) *GoodInfoUpdateOne {
	mutation := newGoodInfoMutation(c.config, OpUpdateOne, withGoodInfoID(id))
	return &GoodInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GoodInfo.
func (c *GoodInfoClient) Delete() *GoodInfoDelete {
	mutation := newGoodInfoMutation(c.config, OpDelete)
	return &GoodInfoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *GoodInfoClient) DeleteOne(gi *GoodInfo) *GoodInfoDeleteOne {
	return c.DeleteOneID(gi.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *GoodInfoClient) DeleteOneID(id uuid.UUID) *GoodInfoDeleteOne {
	builder := c.Delete().Where(goodinfo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GoodInfoDeleteOne{builder}
}

// Query returns a query builder for GoodInfo.
func (c *GoodInfoClient) Query() *GoodInfoQuery {
	return &GoodInfoQuery{
		config: c.config,
	}
}

// Get returns a GoodInfo entity by its id.
func (c *GoodInfoClient) Get(ctx context.Context, id uuid.UUID) (*GoodInfo, error) {
	return c.Query().Where(goodinfo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GoodInfoClient) GetX(ctx context.Context, id uuid.UUID) *GoodInfo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GoodInfoClient) Hooks() []Hook {
	return c.hooks.GoodInfo
}

// TargetAreaClient is a client for the TargetArea schema.
type TargetAreaClient struct {
	config
}

// NewTargetAreaClient returns a client for the TargetArea from the given config.
func NewTargetAreaClient(c config) *TargetAreaClient {
	return &TargetAreaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `targetarea.Hooks(f(g(h())))`.
func (c *TargetAreaClient) Use(hooks ...Hook) {
	c.hooks.TargetArea = append(c.hooks.TargetArea, hooks...)
}

// Create returns a create builder for TargetArea.
func (c *TargetAreaClient) Create() *TargetAreaCreate {
	mutation := newTargetAreaMutation(c.config, OpCreate)
	return &TargetAreaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TargetArea entities.
func (c *TargetAreaClient) CreateBulk(builders ...*TargetAreaCreate) *TargetAreaCreateBulk {
	return &TargetAreaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TargetArea.
func (c *TargetAreaClient) Update() *TargetAreaUpdate {
	mutation := newTargetAreaMutation(c.config, OpUpdate)
	return &TargetAreaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TargetAreaClient) UpdateOne(ta *TargetArea) *TargetAreaUpdateOne {
	mutation := newTargetAreaMutation(c.config, OpUpdateOne, withTargetArea(ta))
	return &TargetAreaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TargetAreaClient) UpdateOneID(id uuid.UUID) *TargetAreaUpdateOne {
	mutation := newTargetAreaMutation(c.config, OpUpdateOne, withTargetAreaID(id))
	return &TargetAreaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TargetArea.
func (c *TargetAreaClient) Delete() *TargetAreaDelete {
	mutation := newTargetAreaMutation(c.config, OpDelete)
	return &TargetAreaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TargetAreaClient) DeleteOne(ta *TargetArea) *TargetAreaDeleteOne {
	return c.DeleteOneID(ta.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TargetAreaClient) DeleteOneID(id uuid.UUID) *TargetAreaDeleteOne {
	builder := c.Delete().Where(targetarea.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TargetAreaDeleteOne{builder}
}

// Query returns a query builder for TargetArea.
func (c *TargetAreaClient) Query() *TargetAreaQuery {
	return &TargetAreaQuery{
		config: c.config,
	}
}

// Get returns a TargetArea entity by its id.
func (c *TargetAreaClient) Get(ctx context.Context, id uuid.UUID) (*TargetArea, error) {
	return c.Query().Where(targetarea.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TargetAreaClient) GetX(ctx context.Context, id uuid.UUID) *TargetArea {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TargetAreaClient) Hooks() []Hook {
	return c.hooks.TargetArea
}
