// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/cloud-hashing-goods/pkg/db/ent/vendorlocation"
	"github.com/google/uuid"
)

// VendorLocationQuery is the builder for querying VendorLocation entities.
type VendorLocationQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.VendorLocation
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VendorLocationQuery builder.
func (vlq *VendorLocationQuery) Where(ps ...predicate.VendorLocation) *VendorLocationQuery {
	vlq.predicates = append(vlq.predicates, ps...)
	return vlq
}

// Limit adds a limit step to the query.
func (vlq *VendorLocationQuery) Limit(limit int) *VendorLocationQuery {
	vlq.limit = &limit
	return vlq
}

// Offset adds an offset step to the query.
func (vlq *VendorLocationQuery) Offset(offset int) *VendorLocationQuery {
	vlq.offset = &offset
	return vlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vlq *VendorLocationQuery) Unique(unique bool) *VendorLocationQuery {
	vlq.unique = &unique
	return vlq
}

// Order adds an order step to the query.
func (vlq *VendorLocationQuery) Order(o ...OrderFunc) *VendorLocationQuery {
	vlq.order = append(vlq.order, o...)
	return vlq
}

// First returns the first VendorLocation entity from the query.
// Returns a *NotFoundError when no VendorLocation was found.
func (vlq *VendorLocationQuery) First(ctx context.Context) (*VendorLocation, error) {
	nodes, err := vlq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{vendorlocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vlq *VendorLocationQuery) FirstX(ctx context.Context) *VendorLocation {
	node, err := vlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VendorLocation ID from the query.
// Returns a *NotFoundError when no VendorLocation ID was found.
func (vlq *VendorLocationQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = vlq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{vendorlocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vlq *VendorLocationQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := vlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VendorLocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one VendorLocation entity is not found.
// Returns a *NotFoundError when no VendorLocation entities are found.
func (vlq *VendorLocationQuery) Only(ctx context.Context) (*VendorLocation, error) {
	nodes, err := vlq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{vendorlocation.Label}
	default:
		return nil, &NotSingularError{vendorlocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vlq *VendorLocationQuery) OnlyX(ctx context.Context) *VendorLocation {
	node, err := vlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VendorLocation ID in the query.
// Returns a *NotSingularError when exactly one VendorLocation ID is not found.
// Returns a *NotFoundError when no entities are found.
func (vlq *VendorLocationQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = vlq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = &NotSingularError{vendorlocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vlq *VendorLocationQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := vlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VendorLocations.
func (vlq *VendorLocationQuery) All(ctx context.Context) ([]*VendorLocation, error) {
	if err := vlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vlq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vlq *VendorLocationQuery) AllX(ctx context.Context) []*VendorLocation {
	nodes, err := vlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VendorLocation IDs.
func (vlq *VendorLocationQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := vlq.Select(vendorlocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vlq *VendorLocationQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := vlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vlq *VendorLocationQuery) Count(ctx context.Context) (int, error) {
	if err := vlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vlq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vlq *VendorLocationQuery) CountX(ctx context.Context) int {
	count, err := vlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vlq *VendorLocationQuery) Exist(ctx context.Context) (bool, error) {
	if err := vlq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vlq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vlq *VendorLocationQuery) ExistX(ctx context.Context) bool {
	exist, err := vlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VendorLocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vlq *VendorLocationQuery) Clone() *VendorLocationQuery {
	if vlq == nil {
		return nil
	}
	return &VendorLocationQuery{
		config:     vlq.config,
		limit:      vlq.limit,
		offset:     vlq.offset,
		order:      append([]OrderFunc{}, vlq.order...),
		predicates: append([]predicate.VendorLocation{}, vlq.predicates...),
		// clone intermediate query.
		sql:  vlq.sql.Clone(),
		path: vlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VendorLocation.Query().
//		GroupBy(vendorlocation.FieldCountry).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (vlq *VendorLocationQuery) GroupBy(field string, fields ...string) *VendorLocationGroupBy {
	group := &VendorLocationGroupBy{config: vlq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vlq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Country string `json:"country,omitempty"`
//	}
//
//	client.VendorLocation.Query().
//		Select(vendorlocation.FieldCountry).
//		Scan(ctx, &v)
//
func (vlq *VendorLocationQuery) Select(fields ...string) *VendorLocationSelect {
	vlq.fields = append(vlq.fields, fields...)
	return &VendorLocationSelect{VendorLocationQuery: vlq}
}

func (vlq *VendorLocationQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vlq.fields {
		if !vendorlocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if vlq.path != nil {
		prev, err := vlq.path(ctx)
		if err != nil {
			return err
		}
		vlq.sql = prev
	}
	return nil
}

func (vlq *VendorLocationQuery) sqlAll(ctx context.Context) ([]*VendorLocation, error) {
	var (
		nodes = []*VendorLocation{}
		_spec = vlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &VendorLocation{config: vlq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, vlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (vlq *VendorLocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vlq.querySpec()
	return sqlgraph.CountNodes(ctx, vlq.driver, _spec)
}

func (vlq *VendorLocationQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := vlq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (vlq *VendorLocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   vendorlocation.Table,
			Columns: vendorlocation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: vendorlocation.FieldID,
			},
		},
		From:   vlq.sql,
		Unique: true,
	}
	if unique := vlq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vlq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vendorlocation.FieldID)
		for i := range fields {
			if fields[i] != vendorlocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vlq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vlq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vlq *VendorLocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vlq.driver.Dialect())
	t1 := builder.Table(vendorlocation.Table)
	columns := vlq.fields
	if len(columns) == 0 {
		columns = vendorlocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if vlq.sql != nil {
		selector = vlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range vlq.predicates {
		p(selector)
	}
	for _, p := range vlq.order {
		p(selector)
	}
	if offset := vlq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vlq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VendorLocationGroupBy is the group-by builder for VendorLocation entities.
type VendorLocationGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vlgb *VendorLocationGroupBy) Aggregate(fns ...AggregateFunc) *VendorLocationGroupBy {
	vlgb.fns = append(vlgb.fns, fns...)
	return vlgb
}

// Scan applies the group-by query and scans the result into the given value.
func (vlgb *VendorLocationGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := vlgb.path(ctx)
	if err != nil {
		return err
	}
	vlgb.sql = query
	return vlgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := vlgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VendorLocationGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) StringsX(ctx context.Context) []string {
	v, err := vlgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vlgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) StringX(ctx context.Context) string {
	v, err := vlgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VendorLocationGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) IntsX(ctx context.Context) []int {
	v, err := vlgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vlgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) IntX(ctx context.Context) int {
	v, err := vlgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VendorLocationGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := vlgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vlgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) Float64X(ctx context.Context) float64 {
	v, err := vlgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(vlgb.fields) > 1 {
		return nil, errors.New("ent: VendorLocationGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := vlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := vlgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vlgb *VendorLocationGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vlgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vlgb *VendorLocationGroupBy) BoolX(ctx context.Context) bool {
	v, err := vlgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vlgb *VendorLocationGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range vlgb.fields {
		if !vendorlocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vlgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vlgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vlgb *VendorLocationGroupBy) sqlQuery() *sql.Selector {
	selector := vlgb.sql.Select()
	aggregation := make([]string, 0, len(vlgb.fns))
	for _, fn := range vlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(vlgb.fields)+len(vlgb.fns))
		for _, f := range vlgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(vlgb.fields...)...)
}

// VendorLocationSelect is the builder for selecting fields of VendorLocation entities.
type VendorLocationSelect struct {
	*VendorLocationQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (vls *VendorLocationSelect) Scan(ctx context.Context, v interface{}) error {
	if err := vls.prepareQuery(ctx); err != nil {
		return err
	}
	vls.sql = vls.VendorLocationQuery.sqlQuery(ctx)
	return vls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vls *VendorLocationSelect) ScanX(ctx context.Context, v interface{}) {
	if err := vls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) Strings(ctx context.Context) ([]string, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VendorLocationSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vls *VendorLocationSelect) StringsX(ctx context.Context) []string {
	v, err := vls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vls *VendorLocationSelect) StringX(ctx context.Context) string {
	v, err := vls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) Ints(ctx context.Context) ([]int, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VendorLocationSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vls *VendorLocationSelect) IntsX(ctx context.Context) []int {
	v, err := vls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vls *VendorLocationSelect) IntX(ctx context.Context) int {
	v, err := vls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VendorLocationSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vls *VendorLocationSelect) Float64sX(ctx context.Context) []float64 {
	v, err := vls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vls *VendorLocationSelect) Float64X(ctx context.Context) float64 {
	v, err := vls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(vls.fields) > 1 {
		return nil, errors.New("ent: VendorLocationSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := vls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vls *VendorLocationSelect) BoolsX(ctx context.Context) []bool {
	v, err := vls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (vls *VendorLocationSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{vendorlocation.Label}
	default:
		err = fmt.Errorf("ent: VendorLocationSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vls *VendorLocationSelect) BoolX(ctx context.Context) bool {
	v, err := vls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vls *VendorLocationSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := vls.sql.Query()
	if err := vls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
