// Code generated by entc, DO NOT EDIT.

package feetype

import (
	"fmt"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the feetype type in the database.
	Label = "fee_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFeeType holds the string denoting the fee_type field in the database.
	FieldFeeType = "fee_type"
	// FieldFeeDescription holds the string denoting the fee_description field in the database.
	FieldFeeDescription = "fee_description"
	// FieldPayType holds the string denoting the pay_type field in the database.
	FieldPayType = "pay_type"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldUpdateAt holds the string denoting the update_at field in the database.
	FieldUpdateAt = "update_at"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// Table holds the table name of the feetype in the database.
	Table = "fee_types"
)

// Columns holds all SQL columns for feetype fields.
var Columns = []string{
	FieldID,
	FieldFeeType,
	FieldFeeDescription,
	FieldPayType,
	FieldCreateAt,
	FieldUpdateAt,
	FieldDeleteAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FeeDescriptionValidator is a validator for the "fee_description" field. It is called by the builders before save.
	FeeDescriptionValidator func(string) error
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() uint32
	// DefaultUpdateAt holds the default value on creation for the "update_at" field.
	DefaultUpdateAt func() uint32
	// UpdateDefaultUpdateAt holds the default value on update for the "update_at" field.
	UpdateDefaultUpdateAt func() uint32
	// DefaultDeleteAt holds the default value on creation for the "delete_at" field.
	DefaultDeleteAt func() uint32
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PayType defines the type for the "pay_type" enum field.
type PayType string

// PayType values.
const (
	PayTypePercent PayType = "percent"
	PayTypeAmount  PayType = "amount"
)

func (pt PayType) String() string {
	return string(pt)
}

// PayTypeValidator is a validator for the "pay_type" field enum values. It is called by the builders before save.
func PayTypeValidator(pt PayType) error {
	switch pt {
	case PayTypePercent, PayTypeAmount:
		return nil
	default:
		return fmt.Errorf("feetype: invalid enum value for pay_type field: %q", pt)
	}
}
