// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CloudHashingGoodsClient is the client API for CloudHashingGoods service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudHashingGoodsClient interface {
	Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error)
}

type cloudHashingGoodsClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudHashingGoodsClient(cc grpc.ClientConnInterface) CloudHashingGoodsClient {
	return &cloudHashingGoodsClient{cc}
}

func (c *cloudHashingGoodsClient) Echo(ctx context.Context, in *StringMessage, opts ...grpc.CallOption) (*StringMessage, error) {
	out := new(StringMessage)
	err := c.cc.Invoke(ctx, "/cloud.hashing.goods.v1.CloudHashingGoods/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudHashingGoodsServer is the server API for CloudHashingGoods service.
// All implementations must embed UnimplementedCloudHashingGoodsServer
// for forward compatibility
type CloudHashingGoodsServer interface {
	Echo(context.Context, *StringMessage) (*StringMessage, error)
	mustEmbedUnimplementedCloudHashingGoodsServer()
}

// UnimplementedCloudHashingGoodsServer must be embedded to have forward compatible implementations.
type UnimplementedCloudHashingGoodsServer struct {
}

func (UnimplementedCloudHashingGoodsServer) Echo(context.Context, *StringMessage) (*StringMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedCloudHashingGoodsServer) mustEmbedUnimplementedCloudHashingGoodsServer() {}

// UnsafeCloudHashingGoodsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudHashingGoodsServer will
// result in compilation errors.
type UnsafeCloudHashingGoodsServer interface {
	mustEmbedUnimplementedCloudHashingGoodsServer()
}

func RegisterCloudHashingGoodsServer(s grpc.ServiceRegistrar, srv CloudHashingGoodsServer) {
	s.RegisterService(&CloudHashingGoods_ServiceDesc, srv)
}

func _CloudHashingGoods_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudHashingGoodsServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloud.hashing.goods.v1.CloudHashingGoods/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudHashingGoodsServer).Echo(ctx, req.(*StringMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudHashingGoods_ServiceDesc is the grpc.ServiceDesc for CloudHashingGoods service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudHashingGoods_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud.hashing.goods.v1.CloudHashingGoods",
	HandlerType: (*CloudHashingGoodsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _CloudHashingGoods_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/cloud-hashing-goods.proto",
}
