// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppGood is the predicate function for appgood builders.
type AppGood func(*sql.Selector)

// AppGoodTargetArea is the predicate function for appgoodtargetarea builders.
type AppGoodTargetArea func(*sql.Selector)

// AppTargetArea is the predicate function for apptargetarea builders.
type AppTargetArea func(*sql.Selector)

// DeviceInfo is the predicate function for deviceinfo builders.
type DeviceInfo func(*sql.Selector)

// GoodComment is the predicate function for goodcomment builders.
type GoodComment func(*sql.Selector)

// GoodExtraInfo is the predicate function for goodextrainfo builders.
type GoodExtraInfo func(*sql.Selector)

// GoodFee is the predicate function for goodfee builders.
type GoodFee func(*sql.Selector)

// GoodInfo is the predicate function for goodinfo builders.
type GoodInfo func(*sql.Selector)

// GoodReview is the predicate function for goodreview builders.
type GoodReview func(*sql.Selector)

// PriceCurrency is the predicate function for pricecurrency builders.
type PriceCurrency func(*sql.Selector)

// TargetArea is the predicate function for targetarea builders.
type TargetArea func(*sql.Selector)

// VendorLocation is the predicate function for vendorlocation builders.
type VendorLocation func(*sql.Selector)
